%define	module	Package-Constants
%define name	perl-%{module}
%define	modprefix Package

%define version 0.01

%define	rel	1
%define release %mkrel %{rel}

Summary:	Package Constants
Name:		%{name}
Version:	%{version}
Release:	%{release}
License:	Artistic/GPL
Group:		Development/Perl
URL:		http://search.cpan.org/dist/%{module}/
Source:		ftp://ftp.perl.org/pub/CPAN/modules/by-module/%{modprefix}/%{module}-%{version}.tar.gz
%if %{mdkversion} < 1010
BuildRequires:	perl-devel >= 5.8.1
%endif
BuildArch:	noarch


%description
"Package::Constants" lists all the constants defined in a certain pack- age.
This can be useful for, among others, setting up an autogenerated
"@EXPORT/@EXPORT_OK" for a Constants.pm file.

%prep
%setup -q -n %{module}-%{version}

%build
%__perl Makefile.PL INSTALLDIRS=vendor
%make

%check
%__make test

%install
rm -rf %{buildroot}
%makeinstall_std

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root)
%doc README
%{perl_vendorlib}/%{modprefix}/*
%{_mandir}/*/*
